spring:
  application:
    name: auth-server
    # server:
    #     port: 8080


  datasource:
    url: jdbc:postgresql://ep-fragrant-hill-afuz31pf-pooler.c-2.us-west-2.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_WUEZbnY0Gr8F
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true




    